name: vemare
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+11

environment:
  sdk: ">=2.18.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  chewie: ^1.4.0
  flutter_svg: ^1.0.3
  group_radio_button: ^1.3.0
  nested_scroll_views: ^0.0.6
  dropdown_button2: ^2.0.0
  video_player: ^2.5.3
  freezed_annotation: ^2.1.0 
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  http: ^0.13.4
  shimmer: ^2.0.0
  slide_to_confirm: ^1.1.0
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0
  table_calendar: ^3.0.8
  dropdown_search: ^5.0.5
  flutter_swiper_null_safety: ^1.0.2
  flutter_multi_formatter: ^2.10.2
  file_picker: ^4.6.1
  money_formatter: ^0.0.3
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  intl: ^0.17.0
  timeago: ^3.3.0
  animate_do: ^3.0.2
  flutter_html: ^3.0.0-alpha.6
  dio: ^5.1.1
  signature: ^5.3.0
  flutter_localizations:
    sdk: flutter
  flutter_rounded_date_picker: 3.0.2
  # android_path_provider: ^0.3.0
  # flutter_downloader: ^1.10.2
  path_provider: ^2.0.14
  open_file: ^3.2.1
  location: ^4.4.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  
  
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  freezed: ^2.0.4
  

 
  very_good_analysis: ^3.1.0
  flutter_lints: ^2.0.1
  


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/imgs/
    - assets/mp4/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Black.ttf
        - asset: assets/fonts/NunitoSans-Bold.ttf
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-Light.ttf
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
