final List<String> countries = [
  "A Coruña",
  "Albacete",
  "Alcalá de Henares",
  "Alcobendas",
  "Alcorcón",
  "Algeciras",
  "Alicante",
  "Almería",
  "Aranjuez",
  "Arganda del Rey",
  "Badajoz",
  "Badalona",
  "Barcelona",
  "Benalmádena",
  "Benidorm",
  "Bilbao",
  "Burgos",
  "Cáceres",
  "Cádiz",
  "Calp",
  "Cartagena",
  "Castelldefels",
  "Castellón de la Plana",
  "Ceuta",
  "Chiclana de la Frontera",
  "Ciudad Real",
  "Córdoba",
  "Cornellà de Llobregat",
  "Coslada",
  "Cuenca",
  "Dos Hermanas",
  "Eibar",
  "Elche",
  "El Ejido",
  "Estepona",
  "Ferrol",
  "Fuenlabrada",
  "Gandia",
  "Getafe",
  "Gijón",
  "Girona",
  "Granada",
  "Granollers",
  "Guadalajara",
  "Huelva",
  "Hospitalet de Llobregat",
  "Huesca",
  "Ibiza",
  "Jaén",
  "Jerez de la Frontera",
  "La Línea de la Concepción",
  "Las Palmas de Gran Canaria",
  "Leganés",
  "León",
  "Lleida",
  "Logroño",
  "Lugo",
  "Madrid",
  "Málaga",
  "Manresa",
  "Marbella",
  "Mataró",
  "Mérida",
  "Mijas",
  "Móstoles",
  "Murcia",
  "Orense (Ourense)",
  "Oviedo",
  "Palencia",
  "Palma de Mallorca",
  "Pamplona",
  "Parla",
  "Ponferrada",
  "Pontevedra",
  "Puerto de la Cruz",
  "Reus",
  "Roquetas de Mar",
  "Sabadell",
  "Salamanca",
  "San Cristóbal de La Laguna",
  "San Fernando",
  "San Sebastián",
  "Santa Coloma de Gramenet",
  "Santa Cruz de Tenerife",
  "Santander",
  "Santiago de Compostela",
  "Segovia",
  "Sevilla",
  "Soria",
  "Tarragona",
  "Telde",
  "Terrassa",
  "Toledo",
  "Torrejón de Ardoz",
  "Torremolinos",
  "Torrevieja",
  "Valencia",
  "Valladolid",
  "Vélez-Málaga",
  "Vigo",
  "Vila-real",
  "Viladecans",
  "Vitoria-Gasteiz",
  "Zamora",
  "Zaragoza",
];
